<section class="secciongeneral" id="cedis">
    <div class="title-section margin-bot-50">
        <hr>
        <h2>Centros de Distribucion</h2>
    </div>

    <div class="seccion-cdis">
        <div class="mapa_imagen">
            <img src="img/Centros/genayar.jpg" class="imgcentros" usemap="#mapa1"/> 
            
            <ul class="ubicacion">
                <li id="notaL1"><span class="color-dialog"><em>ACAPONETA</em></br>
                    <p>&nbsp;<br/>
                        Carretera Federal #15<br/> 
                        México-Nogales km 1042 <br/>
                        Nayarit, México<br/>
                        Tel. 01 325 25 2 04 65<br/>
                        </br>
                        <img id="mini_cede" src="img/Centros/Acaponeta.jpg"/>
                    </p></span></li>
                <li id="notaL2"><span class="color-dialog"><em>TUXPAN</em>
                    <p>&nbsp;<br/>
                        Gallegos #2<br/> 
                        Col. Emiliano Zapata <br/>
                        Nayarit, México<br/>
                        Tel. 01 319 23 2 08 31<br/>
                        </br>
                        <img id="mini_cede" src="img/Centros/Tuxpan.jpg"/>
                    </p></span></li>
                <li id="notaL3"><span class="color-dialog"><em>SANTIAGO</em>
                        <p>&nbsp;<br/>
                        Segunda Corregidora y Nicolas Echevarria S/N<br/>
                        Col. Centro<br/>
                        Nayarit, México<br/>
                        Tel. 01 323 23 5 02 68<br/>
                        </br>
                        <img id="mini_cede" src="img/Centros/Santiago.jpg"/>
                        </p></span></li>
                <li id="notaL4"><span class="color-dialog"><em>VILLA HIDALGO</em>
                        <p>&nbsp;<br/>
                        Carretera a Villa Hidalgo #960 <br/>
                        Nayarit, México<br/>
                        Tel. 01 323 23 6 21 43<br/>
                        </br>
                        <img id="mini_cede" src="img/Centros/Villa.jpg"/>
                        </p></span></li>
                </ul>
                <ul class="ubicacion2">
                <li id="notaL1"><span class="color-dialog"><em>TEPIC</em>
                        <p>&nbsp;<br/>
                        Av. Insurgentes #1100 <br/>
                        Colonia. Los Llanitos<br/>
                        Tepic, Nayarit, México<br/>
                        Tel.211 97 00</br>
                        </br>
                        <img id="mini_cede" src="img/Centros/mini_cede.jpg"/>
                        </p></span></li>
                </ul>
                <ul class="ubicacion3">
                <li id="notaL1"><span class="color-dialog"><em>COMPOSTELA</em>
                        <p>&nbsp;<br/>
                        Carretera a chapalilla km.32<br/>
                        Nayarit, México<br/>
                        Tel.01327-27-7-03-12</br>
                        </br>
                        <img id="mini_cede" src="img/Centros/Compostela.jpg"/>
                        </p></span></li>

                <li id="notaL2"><span class="color-dialog"><em>LAS VARAS</em>
                        <p>&nbsp;<br/>
                        Av. Lopez Mateos s/n<br/>
                        Col. Celso Hernandez<br/>
                        Nayarit, México<br/>
                        Tel. 01327-27-2-01-28 </br>
                        </br>
                            <img id="mini_cede" src="img/Centros/Varas.jpg"/>
                        </p></span></li>    
                <li id="notaL3"><span class="color-dialog"><em>LA PEÑITA</em>
                        <p>&nbsp;<br/>
                        Martin Pinzon y Oceano Pacifico s/n<br/>
                        Nayarit, México<br/>
                        Tel. 01327-27-4-08-59 </br>
                        </br>
                        <img id="mini_cede" src="img/Centros/Penita.jpg"/>
                        </p></span></li>
                <li id="notaL4"><span class="color-dialog"><em>IXTLAN</em>
                        <p>&nbsp;<br/>
                        Av. Hidalgo 1211 pte<br/>
                        Col. La moderna<br/>
                        Nayarit. México<br/>
                        Tel. 01 324 24 3 23 71</br>
                        </br>
                        <img id="mini_cede" src="img/Centros/Ixtlan.jpg"/>
                        </p></span></li>
                <li id="notaL5"><span class="color-dialog"><em>EL ROSARIO</em>
                        <p>&nbsp;<br/>
                        Juárez 16 b<br/>
                        Col. Centro <br/>
                        Nayarit. México<br/>
                        Tel. 01 324 24 1 60 98</br>
                        </br>
                        <img id="mini_cede" src="img/Centros/Rosario.jpg"/>
                        </p></span></li> 
            </ul>
            <ul class="ubicacion4">
                <li id="notaL1">
                    <span class="color-dialog"><em>SAN VICENTE</em>
                    <p>&nbsp;<br/>
                        Carretera a Mezcales No. 1249<br/>
                        CP.63737 Mpo. Bahia de Banderas Nayarit<br/>
                        Nayarit, México
                        Tel. 01-329-2 26 84 00<br/>
                        </br>
                        <img id="mini_cede" src="img/Centros/San_Vicente.jpg"/>
                    </p></span></li>
            </ul>
            <ul class="ubicacion5">
                <li id="notaL1">
                        <span class="color-dialog"><em>PUERTO VALLARTA.</em>
                        <p>&nbsp;<br/>
                        Carretera Tepic #4660<br/>
                        Col. Gpe. Victoria<br/>
                        Nayarit, México<br/>
                        Tel. 01322-22-108-95 Y 99</br>
                        </br>
                        <img id="mini_cede" src="img/Centros/Vallarta.jpg"/>
                        </p></span></li>
            </ul>
        </div>
    </div>

    <div class="acordeon"> 
        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/ac.png" alt="" srcset=""> ACAPONETA</h2>
            <p class="acordeon__contenido"> 
                Carretera Federal #15<br> 
                México-Nogales km 1042 <br>
                Nayarit, México<br>
                Tel. 01 325 25 2 04 65<br>
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/tx.png" alt="" srcset=""> TUXPAN</h2>
            <p class="acordeon__contenido"> 
                Gallegos #2<br> 
                Col. Emiliano Zapata <br>
                Nayarit, México<br>
                Tel. 01 319 23 2 08 31
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/sn.png" alt="" srcset=""> SANTIAGO</h2>
            <p class="acordeon__contenido"> 
                Segunda Corregidora y Nicolas Echevarria S/N<br>
                Col. Centro<br>
                Nayarit, México<br>
                Tel. 01 323 23 5 02 68
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/vh.png" alt="" srcset=""> VILLA HIDALGO</h2>
            <p class="acordeon__contenido"> 
                Carretera a Villa Hidalgo #960 <br>
                Nayarit, México<br>
                Tel. 01 323 23 6 21 43
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/tp.png" alt="" srcset=""> TEPIC</h2>
            <p class="acordeon__contenido"> 
                Av. Insurgentes #1100 <br>
                Colonia. Los Llanitos<br>
                Tepic, Nayarit, México<br>
                Tel.211 97 00
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/cm.png" alt="" srcset=""> COMPOSTELA</h2>
            <p class="acordeon__contenido"> 
                Carretera a chapalilla km.32<br>
                Nayarit, México<br>
                Tel.01327-27-7-03-12
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/lv.png" alt="" srcset=""> LAS VARAS</h2>
            <p class="acordeon__contenido"> 
                Av. Lopez Mateos s/n<br>
                Col. Celso Hernandez<br>
                Nayarit, México<br>
                Tel. 01327-27-2-01-28
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/lp.png" alt="" srcset=""> LA PEÑITA</h2>
            <p class="acordeon__contenido"> 
                Martin Pinzon y Oceano Pacifico s/n<br>
                Nayarit, México<br>
                Tel. 01327-27-4-08-59
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/ix.png" alt="" srcset=""> IXTLAN</h2>
            <p class="acordeon__contenido"> 
                Av. Hidalgo 1211 pte<br>
                Col. La moderna<br>
                Nayarit. México<br>
                Tel. 01 324 24 3 23 71
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/rs.png" alt="" srcset=""> EL ROSARIO</h2>
            <p class="acordeon__contenido"> 
                Juárez 16 b<br>
                Col. Centro <br>
                Nayarit. México<br>
                Tel. 01 324 24 1 60 98
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/sv.png" alt="" srcset=""> SAN VICENTE</h2>
            <p class="acordeon__contenido"> 
                Carretera a Mezcales No. 1249<br>
                CP.63737 Mpo. Bahia de Banderas Nayarit<br>
                Nayarit, México<br>
                Tel. 01-329-2 26 84 00
            </p>
        </div>

        <div class="acordeon__contenedor">
            <h2 class="acordeon__titulo"><img src="./img/pv.png" alt="" srcset=""> PUERTO VALLARTA</h2>
            <p class="acordeon__contenido"> 
                Carretera Tepic #4660<br>
                Col. Gpe. Victoria<br>
                Nayarit, México<br>
                Tel. 01322-22-108-95 Y 99
            </p>
        </div>
    </div>
</section>